### PR TITLE
made a fresh branch and adjusted file names...

### PR DESCRIPTION
**Pull request by mahydraal**
I have added a few gifs and adjusted capitalization in file names. 
Is this the correct way to create edits for review when submitting large numbers of changes ?

### CODE REVIEW

**Review by JMeyerEngineering — COMMENTED** [review]
I'm not that familiar with the workings of github, but I want to present what I see. 

Several bins show they are unable to render code block.

image

**Comment by KenVanHoeylandt** [comment]
@JMeyerEngineering Perhaps a GitHub fluke? Works fine here:
image

**Comment by KenVanHoeylandt** [comment]
@mahydraal Looks good to me! :+1: 
Will you update the references in the `assembly.md` separately or also in this PR?

**Review by KenVanHoeylandt — APPROVED** [review]

**Comment by mahydraal** [comment]
thanks!
When you say update the references separately, what do you mean?

You mean the references in the doc directory so it actually is visible?

**Pull request merged**
